server:
 port: 8080

#druid连接池配置
druid:
  url: jdbc:h2:tcp://localhost:9092/~/test  username: sa
  password: 123456
  max-active: 100 #最大连接池数量
  min-idle: 10    #最小连接池数量
  testWhileIdle: true       